version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tasks_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tasks_db
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
